name: Unity Asset Notifier

on:
  schedule:
    # Runs at 15:30, and 16:30 UTC every Thursday
    # This covers 7:30/8:30 PT in both summer and winter
    - cron: '30 15,16 * * 4'
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 emailoctopus-sdk

      - name: Run the notifier script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          LIST_ID: ${{ secrets.LIST_ID }}
          RUN_CONTEXT: ${{ github.event_name }}
        run: python main.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update total savings"
          file_pattern: "savings.json"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions@github.com"
          commit_author: "GitHub Actions Bot <github-actions@github.com>"